// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_1001_EF_Primer.Web_1001_EF_Primer.Data;

#nullable disable

namespace Web_1001_EF_Primer.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20230804214112_AddingCommentDateIndex")]
    partial class AddingCommentDateIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.19");

            modelBuilder.Entity("Web_1001_EF_Primer.Web_1001_EF_Primer.Models.Entities.BlogPost", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EditorsNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Web_1001_EF_Primer.Web_1001_EF_Primer.Models.Entities.Comment", b =>
                {
                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlogUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Author", "CommentDate", "BlogUrl")
                        .HasName("PK_Comments");

                    b.HasIndex("BlogUrl");

                    b.HasIndex("CommentDate")
                        .HasDatabaseName("IX_Comment_CommentDate");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Web_1001_EF_Primer.Web_1001_EF_Primer.Models.Entities.Comment", b =>
                {
                    b.HasOne("Web_1001_EF_Primer.Web_1001_EF_Primer.Models.Entities.BlogPost", "Post")
                        .WithMany()
                        .HasForeignKey("BlogUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
